config/routes.rb
AppEad::Application.routes.draw do

  resources :courses, :only => %w(index show)

  scope "/app" do
    devise_for :users, :controllers => { :sessions => "admin/sessions", 
                                         :registrations => "admin/registrations", 
                                         :passwords => "admin/passwords" 
                                       }, 
      :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }, 
      :path => "/"
  end
    
  namespace :admin, :path => "app/" do
    root :to => "home#index"
    resources :token_authentications, :only => [:create, :destroy]
    resources :users do
      get :allusers, :on => :collection
    end
    resources :forums do
      resources :messages
    end
    resources :assets, :except => :show
    resources :courses do
      resources :lessons, :except => [:index, :show]
      get :matriculations, :on => :member
      resource :chats do
        get :history, :on => :member
      end
    end
    resources :lessons, :except => [:new, :destroy] do
      get :copy, :on => :member
    end
    match "lesson/:lesson_id/viewlist" => "audit#index", :as => :audit_lesson
    match "alert/:alert_id/viewlist" => "audit#index", :as => :audit_alert
    resources :matriculations
    resources :alerts
  end
  root :to => "pages#index"
  

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController

  menu_item :home
  
  def index
    if current_user.admin?
      @matriculations = Matriculation.where(:enabled => false)
      @matriculations = @matriculations.where(:course_id => params[:course_id]) if !params[:course_id].nil?
      @courses = Course.where(:enabled => true)
      
    else
      if params[:date_at].nil?
        @courses = current_user.courses if current_user.teacher?
        @courses = current_user.tutors if current_user.tutor?
        
        @matriculations = current_user.matriculations if current_user.student?
        
        @alerts = Alert.joins(
                    :course => :matriculations).where(
                      "matriculations.user_id = ? AND alerts.created_at > ? AND matriculations.enabled = true",
                      current_user.id, Time.at(params[:after].to_i + 1)
                    ).paginate(:page => params[:page], :per_page => 5)  if can? :read, Alert
      end
      
      @lessons = current_user.teacher? ? 
                  current_user.lessons.where(:date_at => date_params).all : 
                  current_user.tutor? ?
                  Lesson.joins(:course).where("courses.tutor_id = ? AND date_at = ?", current_user.id, date_params).all :
                  Lesson.joins(
                    :course => :matriculations).where( 
                      :enabled => true,
                      :matriculations => {:user_id => current_user.id, :enabled => true},
                      :date_at => date_params
                    ).all if can? :read, Lesson
                    
     @lessons_temp = current_user.teacher? ? 
                      current_user.lessons.where("date_at > ?", date_params).order("date_at").limit(5) : 
                      current_user.tutor? ?
                      Lesson.joins(:course).where("courses.tutor_id = ? AND date_at > ?", current_user.id, date_params).order("date_at").limit(5) :
                      Lesson.joins(
                        :course => :matriculations).where( 
                          "date_at > ? AND lessons.enabled = true AND matriculations.user_id = ? AND matriculations.enabled = true", 
                          date_params, current_user.id
                        ).order("date_at").limit(5) if can? :read, Lesson
    end
  end
   
private
  def date_params 
    (params[:date_at].nil? ? Date.today : params[:date_at].to_date)
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/views/admin/home/_alert.html.erb
<tr class="header alert <%= 'bold' if !alert.opened_alert?(current_user.id) %>" data-time="<%= alert.created_at.to_i %>" data-id="<%= alert.id %>">
  <td width="50%"><%= truncate(alert.title, :length => 30) %></td>
  <td width="40%"><%= l(alert.created_at) %></td>
  <td class="right">
    <%= link_to admin_alert_path(alert) do %>
      <%= image_tag("/images/icons/eye.png", :title => "Ver mensagem", :class => "toolTip")%>
    <% end %>
  </td>
</tr>

app/views/admin/home/_course.html.erb
<%= content_tag_for :tr, course, :class => "header" do %>
<td width="50%"><%= course.name.capitalize %></td>
<td width="40%"></td>
<td class="right">
  <%= link_to image_tag("door_in.png", :size => "18x18"), [:admin, course], :title => "Entrar", :class => "toolTip" %>
  <%= link_to_edit(edit_admin_course_path(course)) if can? :update, Course %>
  <%= link_to_destroy([:admin, course]) if can? :destroy, Course %>
</td>
<% end %>

app/views/admin/home/_lesson.html.erb
<%= content_tag_for :tr, lesson, :class => "header" do %>
  <td width="30%"><%= lesson.theme.capitalize %></td>
    <td width="5%"><%= image_tag("/images/icons/attachment.png", :title => "Anexo", :class => "toolTip") if lesson.assets.present? %></td>
  <td width="10%"><%= lesson.course.name.capitalize %></td>
  <td width="40%"><%= truncate(lesson.description, :length => 50) %></td>
  <td class="right">
    <%= link_to image_tag("/images/icons/view_list.png", :title => "Quem viu", :class => "toolTip"), admin_audit_lesson_path(lesson) if ((can? :read, Audit) && lesson.audits.present?)%>
    <%= link_to image_tag("/images/icons/eye.png", :title => "Ver", :class => "toolTip"), admin_lesson_path(lesson) %>
    <%= link_to_edit([:edit, :admin, lesson]) if can? :update, Lesson %>
  </td>
<% end %>

app/views/admin/home/_lessons_temp.html.erb
<% if @lessons_temp.present? %>
  <i><p>
    <span class="medium">Próximas Aulas</span><br/>
    <% @lessons_temp.group_by(&:date_at).each do |key, temp| %>
      <%= l key %><br/>
    <% end %>
  </p></i>
<% end %>

app/views/admin/home/index.html.erb
<h2 class="education-title">Ambiente <div id="wait" class="right"></div></h2>

<% if @courses.present? && (current_user.teacher? || current_user.tutor?) %>
  <table class="grid">
      <th class="titulo" colspan="3"><h3><%= image_tag("/images/notepad.gif", :size=> "18x18")%> Cursos Ministrados</h3></th>
      <%= render :partial => "course", :collection => @courses %>
  </table>
  <hr class = "thick" />
<% end %>

<% if @matriculations.present? %>
  <table class="grid">
    <%= link_to("Ver lista", admin_matriculations_path, :class => :right) if current_user.admin? %>
    <th class="titulo" colspan="3">
      <h3>
        <%= image_tag("/images/notepad.gif", :size=> "18x18")%> 
        Inscrições 
        <% if current_user.admin? %>
          Pendentes
          <%= select "home", "course_id", @courses.collect { |c| [c.name.capitalize, c.id]}, { :include_blank => "Todos" } %>
        <% end %>
      </h3>
    </th>
  </table>
  
  <table class="grid" id="load">
    <%= render @matriculations %>
  </table>
  
  <hr class = "thick" />
<% end %>

<% if !current_user.admin? && can?(:read, Lesson) %>
  <table class="grid">
    <th class="titulo" colspan="3"><h3><%= image_tag("/images/calendar.png", :size=> "18x18")%> 
    Calendário de Aulas
    </h3>
    </th>
  </table>
  <table class="grid" id="calendar">
    <%= render :partial => "lesson", :collection => @lessons %>
    <% if !@lessons.present? %>
      <tr class="header">
        <td>Não existe aula(s) registrada(s) na data.</td>
      </tr>
    <% end %>
  </table>
  <hr class="thick">
<% end %>

<% if @alerts.present? %>
  <div id="alerts">
    <table class="grid">
      <th class="titulo" colspan="3"><h3><%= image_tag("/images/alert_icon.png", :size=> "18x18")%> Avisos</h3></th>
      <%= render :partial => "alert", :collection => @alerts %>
    </table><br/>
    <%= link_to "Ver todos", admin_alerts_path, :class => "right" %>
  </div>
  <hr class="thick">
<% end %>

<%= content_for :calendar do %>
  <% if can? :read, Lesson %>
    <hr class = "thick" />
    <span class="large title-top">Calendário de Aulas</span>
    <div id="lesson-temp" >
      <%= render :partial => "lessons_temp" %>
    </div>
    <div id="date-ambient" class="datepicker right" ></div>
  <% end %>
<% end %>

app/views/admin/home/index.js.erb
<% if current_user.admin? %>
  $("table#load").html("<%= escape_javascript(render @matriculations) %>");
<% else %>
  <% if @lessons.present? %>
    $("table#calendar").html("<%= escape_javascript(render :partial => 'lesson', :collection => @lessons) %>");
  <% else %>
    $("table#calendar").html("<tr class='header'><td>Não existe aula(s) registrada(s) na data.</td></tr>");
  <% end %>
  
  $("#lesson-temp").html("<%= escape_javascript(render :partial => 'lessons_temp') %>");
  
<% end %>