config/routes.rb
AppEad::Application.routes.draw do

  resources :courses, :only => %w(index show)

  scope "/app" do
    devise_for :users, :controllers => { :sessions => "admin/sessions", 
                                         :registrations => "admin/registrations", 
                                         :passwords => "admin/passwords" 
                                       }, 
      :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }, 
      :path => "/"
  end
    
  namespace :admin, :path => "app/" do
    root :to => "home#index"
    resources :token_authentications, :only => [:create, :destroy]
    resources :users do
      get :allusers, :on => :collection
    end
    resources :forums do
      resources :messages
    end
    resources :assets, :except => :show
    resources :courses do
      resources :lessons, :except => [:index, :show]
      get :matriculations, :on => :member
      resource :chats do
        get :history, :on => :member
      end
    end
    resources :lessons, :except => [:new, :destroy] do
      get :copy, :on => :member
    end
    match "lesson/:lesson_id/viewlist" => "audit#index", :as => :audit_lesson
    match "alert/:alert_id/viewlist" => "audit#index", :as => :audit_alert
    resources :matriculations
    resources :alerts
  end
  root :to => "pages#index"
  

end

app/models/forum.rb
class Forum < ActiveRecord::Base

  belongs_to :user
  has_many :messages, :dependent => :destroy
  accepts_nested_attributes_for :messages, :allow_destroy => true
  
  validates_presence_of :title
  
end

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < Admin::AdminController

  load_and_authorize_resource :message
  load_and_authorize_resource :forum, :through => :message, :shallow => true
  
  menu_item :forums
  
  def index
  end

  def show
  end

  def new
    messages = @forum.messages.build
  end

  def edit
  end

  def create
    @forum.messages.each {|message| message.user_id = current_user.id }
    flash[:notice] = I18n.tm("created", "forum") if @forum.save
    respond_with @forum, :location => admin_forums_url
  end

  def update
    flash[:notice] = I18n.tm("updated", "forum") if @forum.update_attributes(params[:forum])
    respond_with @forum, :location => admin_forums_url
  end

  def destroy
    @forum.destroy
    respond_with @forum, :location => admin_forums_url
  end
end

app/helpers/admin/forums_helper.rb
module Admin::ForumsHelper
  def nested_messages(forums)
    forums.map do |message, sub_messages|
      render(message) + content_tag(:div, nested_messages(sub_messages), :class => "nested_messages")
    end.join.html_safe
  end
end

app/views/admin/forums/_form.html.erb
<%= form_for [:admin, @forum] do |f| %>
  <%= error_messages_for @forum %>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <%= f.fields_for :messages do |builder| %>
    <div class="field">
      <%= builder.label :content %>
      <%= builder.text_area :content, :rows => 8 %>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

<%= link_to t('cancel'), url_for(:back) %>

app/views/admin/forums/_forum.html.erb
<div class="message">
  <div class="created_at"><%= forum.created_at.strftime("%B %d, %Y") %></div>
  <div class="content">
    <%= link_to forum.content, [:admin, forum] %>
  </div>
  <div class="actions">
    <%= link_to "Reply", new_admin_forum_path(:parent_id => forum) %> |
    <%= link_to "Destroy", [:admin, forum], :confirm => "Are you sure?", :method => :delete %>
  </div>
</div>

app/views/admin/forums/edit.html.erb
<h2 class="edit-title">Editar Perguntas</h2>

<%= render 'form' %>

app/views/admin/forums/index.html.erb
<h2 class="chat-title">Fórum
<%= link_to_new(Forum, new_admin_forum_path, "Nova Mensagem") %>
</h2>

<% if @forums.present? %>
<ul class="list">
  <% @forums.each do |forum| %>
    <%= content_tag_for :li, forum, :class => cycle(:odd, :even) do %>
      <%= forum.title %> <span class="hint">Enviado por <%= forum.user.name %>, <%= l forum.created_at %></span>

      <div class="right">
        <%= link_to [:admin, forum, :messages] do %>
          <%= image_tag("/images/icons/eye.png", :title => "Ver mensagens", :class => "toolTip")%>
        <% end %>      
        <%= link_to_edit(edit_admin_forum_path(forum)) if(can? :update, forum) %>
        <%= link_to_destroy([:admin, forum]) if(can? :destroy, forum) %>
      </div>
    <% end %>
  <% end %>
</ul>
<% else %>
  <p>Não existe dúvidas.</p>
<% end %>

<hr class="thick"/>

app/views/admin/forums/new.html.erb
<h2 class="new-title">Nova Pergunta</h2>

<%= render "form" %>

app/views/admin/forums/show.html.erb
<h2 class="chat-title">Mensagem</h2>

<%= nested_messages @forum.subtree.arrange(:order => :created_at) %>

<p><%= link_to "Back to All Messages", admin_forums_path %></p>