config/routes.rb
AppEad::Application.routes.draw do

  resources :courses, :only => %w(index show)

  scope "/app" do
    devise_for :users, :controllers => { :sessions => "admin/sessions", 
                                         :registrations => "admin/registrations", 
                                         :passwords => "admin/passwords" 
                                       }, 
      :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }, 
      :path => "/"
  end
    
  namespace :admin, :path => "app/" do
    root :to => "home#index"
    resources :token_authentications, :only => [:create, :destroy]
    resources :users do
      get :allusers, :on => :collection
    end
    resources :forums do
      resources :messages
    end
    resources :assets, :except => :show
    resources :courses do
      resources :lessons, :except => [:index, :show]
      get :matriculations, :on => :member
      resource :chats do
        get :history, :on => :member
      end
    end
    resources :lessons, :except => [:new, :destroy] do
      get :copy, :on => :member
    end
    match "lesson/:lesson_id/viewlist" => "audit#index", :as => :audit_lesson
    match "alert/:alert_id/viewlist" => "audit#index", :as => :audit_alert
    resources :matriculations
    resources :alerts
  end
  root :to => "pages#index"
  

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  after_find :format_date
  
  default_scope order('created_at desc')

  belongs_to :course 
  belongs_to :user
  has_many :audits, :as => :audit
  
  validates_presence_of :title, :expire, :description
  validates_presence_of :course_id
 
  validate :expire_today
  
  def opened_alert?(user_audit)
    if User.find(user_audit).student?
      self.audits.where(:user_id => user_audit).present?
    else
      true
    end
  end
 
private

  def expire_today
    errors.add(:expire, I18n.t(:cannot_alert_date_expire)) if expire.present? && (expire<Date.today)
  end
  
  def format_date
     self.expire = I18n.l (expire)
  end
end

app/controllers/admin/alerts_controller.rb
class Admin::AlertsController < Admin::AdminController
  
  before_filter :load_resources
  
  menu_item :alerts
  
  load_and_authorize_resource
  
  def index
    @alerts = @alerts.paginate(:page => params[:page], :per_page => 15) if !@alerts.nil?
  end

  def show
    begin
      @audit = @alert.audits.create!(:user_id => current_user.id) if current_user.student?
    rescue
    end
  end

  def new
  end

  def edit
  end

  def create
    flash[:notice] = I18n.tm("created", "alert") if @alert.save
    respond_with @alert, :location => admin_alerts_url
  end

  def update
    flash[:notice] = I18n.tm("updated", "alert") if @alert.update_attributes(params[:alert])
    respond_with @alert, :location => admin_alerts_url
  end

  def destroy
    @alert.destroy
    flash[:notice] = I18n.tm("destroyed", "alert")
    respond_with @alert, :location => admin_alerts_url
  end

private
  def load_resources
    @courses = current_user.courses.activated if current_user.teacher?
    @courses = current_user.tutors.activated if current_user.tutor?
  end
end

app/helpers/admin/alerts_helper.rb
module Admin::AlertsHelper
  
end

app/views/admin/alerts/_form.html.erb
<%= form_for([:admin, @alert]) do |f| %>
  <%= error_messages_for @alert  %>
  
  <div class="field">
    <%= f.label :course_id %>
    <%= collection_select :alert, 
                          :course_id, @courses, :id, 
                          :name,
                          {:include_blank => "Selecione"},
                          {:id => "courses"}
    %>
  </div>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :expire %>
    <%= f.text_field :expire, :class => "datepicker", :size => 15 %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 8 %>
  </div>

  <hr class = "thick" />

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
  
  <%= link_to t('cancel'), url_for(:back) %>
<% end %>

app/views/admin/alerts/edit.html.erb
<h2 class="edit-title">Editar aviso</h2>

<%= render 'form' %>

app/views/admin/alerts/index.html.erb
<h2 class="list-title">Avisos
<%= link_to_new(Alert, new_admin_alert_path) if(can? :create, Alert) && @courses.present? %>
</h2>

<% if @alerts.present? %>
  <table class="grid">
    <ul class="list">
      <% @alerts.each do |alert| %>
        <%= content_tag_for :li, alert, :class => "#{cycle(:odd, :even)} #{(!alert.opened_alert?(current_user.id) ? :bold : :normal)}" do %>
          <%= truncate(alert.title, :length => 30) %>
          <span class="hint">Enviado <%= l alert.created_at %></span>

          <div class="right middle">
            <%= link_to image_tag("/images/icons/view_list.png", :title => "Quem viu", :class => "toolTip"), admin_audit_alert_path(alert) if ((can? :read, Audit) && alert.audits.present?) %>
            <%= link_to image_tag("/images/icons/eye.png", :title => "Ver mensagem", :class => "toolTip"), admin_alert_path(alert) %>
            <%= link_to_edit([:edit, :admin, alert]) if can? :update, Alert %>
            <%= link_to_destroy([:admin, alert]) if can? :destroy, Alert %>
          </div>
        <% end %>
      <% end %>
    </ul>
  </table>
  <%= will_paginate @alerts, :previous_label => "< #{t(:previous_label)}", :next_label => "#{t(:next_label)} >" %>

<% else %>
  <p>Não existe avisos registradas.</p>
<% end %>
<hr class="thick">

app/views/admin/alerts/new.html.erb
<h2 class="new-title">Novo aviso</h2>

<%= render 'form' %>

app/views/admin/alerts/show.html.erb
<h2 class="view-title"><%= @alert.course.name %><span class="hint right">Enviado por <%= @alert.user.name %></span></h2>
<p><strong><i>Assunto:</i></strong> <%= @alert.title.capitalize %></p>
<p><strong><i>Mensagem:</i></strong></p>
<div class="frame"><%= textilize @alert.description %></div>
<hr class = "thick" />