config/routes.rb
AppEad::Application.routes.draw do

  resources :courses, :only => %w(index show)

  scope "/app" do
    devise_for :users, :controllers => { :sessions => "admin/sessions", 
                                         :registrations => "admin/registrations", 
                                         :passwords => "admin/passwords" 
                                       }, 
      :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }, 
      :path => "/"
  end
    
  namespace :admin, :path => "app/" do
    root :to => "home#index"
    resources :token_authentications, :only => [:create, :destroy]
    resources :users do
      get :allusers, :on => :collection
    end
    resources :forums do
      resources :messages
    end
    resources :assets, :except => :show
    resources :courses do
      resources :lessons, :except => [:index, :show]
      get :matriculations, :on => :member
      resource :chats do
        get :history, :on => :member
      end
    end
    resources :lessons, :except => [:new, :destroy] do
      get :copy, :on => :member
    end
    match "lesson/:lesson_id/viewlist" => "audit#index", :as => :audit_lesson
    match "alert/:alert_id/viewlist" => "audit#index", :as => :audit_alert
    resources :matriculations
    resources :alerts
  end
  root :to => "pages#index"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope order('role, name')
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :contact, :cellfone, :home_page, :profile, :role, :email, :password, :password_confirmation, :remember_me
  
  has_and_belongs_to_many :courses
  has_many :matriculations, :dependent => :destroy 
  has_many :assets, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  has_many :alerts, :dependent => :destroy
  has_many :forums, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :tutors, :class_name => "Course", :foreign_key => "tutor_id"
  
  ROLES = %w[admin teacher student tutor]
  
  validates_presence_of :role, :name
  validates_inclusion_of :enabled, :in => [true, false]
  with_options :allow_blank => true do |c|
    c.validates_format_of :home_page,
                    :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  end
   
  #scope :admin, where(:role => ROLES[1])
  scope :teacher, where(:role => ROLES[1])
  scope :tutor, where(:role => ROLES[3])
  
  def teacher?
    self.role == ROLES[1]
  end
  
  def admin?
    self.role == ROLES[0]
  end
  
  def student?
    self.role == ROLES[2]  
  end
  
  def tutor?
    self.role == ROLES[3]
  end
  
  def password_invite(i)
    self.password, self.role = SecureRandom.hex(4), ROLES[i.to_i]
  end
    
protected
  def self.find_for_database_authentication(conditions)
    email = conditions.delete(:email)
    where(conditions).where(["enabled = true AND email = :value", { :value => email }]).first
  end
end

app/controllers/admin/users_controller.rb
# (en)coding: utf-8.
class Admin::UsersController < Admin::AdminController

  load_and_authorize_resource :except => [:show]
  
  menu_item :users
  
  def index
    @users = @users.where("last_sign_in_at >= ? AND last_sign_in_at <= ?", 
                          params[:data_inicio].to_datetime, "#{params[:data_fim]} 23:59:59".to_datetime) if (params[:data_inicio].present? && params[:data_fim].present?)
    @users = @users.where(" course_id = ?", params[:course_id]) if !params[:course_id].nil?
    @users = @users.where(" users.enabled = ?", params[:user_enabled]) if !params[:user_enabled].nil?
    @users = @users.paginate(:page => params[:page], :per_page => 15)
  end
  
  def new
  end
  
  def create
    @user.password_invite(params[:user][:role]) if current_user.admin?

    if @user.save
      flash[:notice] = I18n.tm("created", "user")
      InvitationMailer.registration_teacher(@user).deliver
    end
    respond_with @user, :location => admin_users_url
  end
  
  def show
    @user = User.find(params[:id]) 
  end
    
  def update
    @user.enabled = !@user.enabled
    flash[:notice] = I18n.tm("updated", "user") if @user.update_attributes(params[:user])
    respond_with @user, :location => admin_users_url
  end

  def destroy
    @user.destroy
    flash[:notice] = I18n.tm("destroyed", "user")
    respond_with @user, :location => admin_users_url
  end
  
  def allusers
    respond_to do |format|
      format.html
      format.pdf {
        #render :text => PDFKit.new(allusers_admin_users_url).to_pdf
        html = render_to_string :layout => false, :partial => "usersall.html.erb"
        kit = PDFKit.new("#{html}")
        kit.stylesheets << "#{Rails.root}/public/stylesheets/scaffold.css"
        kit.stylesheets << "#{Rails.root}/public/stylesheets/common.css"
        kit.stylesheets << "#{Rails.root}/public/stylesheets/admin.css"
        send_data kit.to_pdf, :filename => "labels.pdf", :type => 'application/pdf', :disposition => "inline"
        #return # to avoid double render call
      }
    end
  end

 
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  
  <%= error_messages_for @user %>

  <p>
    <%= f.label :role %>
    <%= f.select :role, [[:Professor, 1], [:Tutor, 3]] %>
  </p>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :contact %>
    <%= f.text_field :contact %>
  </p>
  <p>
    <%= f.label :profile %>
    <%= f.text_area :profile, :rows => 5, :cols => 70 %>
  </p>

  <p><%= f.label :email %>
  <%= f.text_field :email %></p>

<hr class="thick" />
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<%= content_tag_for :li, user, :class => cycle(:odd, :even) do %>
  
  <%= user.name %>
  
  <% if user.last_sign_in_at.present? %>
    <span class="hint">Último acesso <%= l user.last_sign_in_at %></span>
  <% end %>
  
  <div class="right">
    <%= link_to admin_user_path(user) do %>
      <%= image_tag("/images/icons/eye.png", :title => "Ver detalhes", :class => "toolTip")%>
    <% end %>  
    <%= link_to_destroy([:admin, user]) if can? :destroy, User %> 
  </div>
  
  <div class="left">
    <% if can? :update, User %>
      <%= form_for([:edit, :admin, user], :remote => true) do |f| %>
        <%= link_to admin_user_path(user), :class => "toolTip", :title => t("user.enabled.#{user.enabled? ? 'desativar' : 'ativar'}"), :method => :put do %>
          <span id = "user-active" class=<%= user.enabled? ? "tick" : "cross" %>></span>
        <% end %> 
      <% end %>
    <% end %>
  </div>
  
<% end %>

app/views/admin/users/_users.html.erb
<% if @users.present? %>
  <% @users.group_by(&:role).each do |container|
    help = (user_group = container.last).first
    title = help.student? ? "Aluno(s)" : help.teacher? ? "Professor(es)" : "Tutor(es)" %>
    <h3><%= title %></h3>
      <ul class="list">
        <%= render :partial => "user", :collection => user_group %>
      </ul>
  <% end %>
  <%= will_paginate @users, :previous_label => "< #{t(:previous_label)}", :next_label => "#{t(:next_label)} >" %>
<% else %>
  <p>Não existe usuários.</p>
<% end %>

app/views/admin/users/_usersall.html.erb
<table class="grid">
  <tr class="header">
    <th>Nome</th>
    <th>Email</th>
    <% if current_user.admin? %>
      <th>Perfil</th>
    <% else %>
      <th>Curso(s)</th>
    <% end %>
    <th>Último Acesso</th>
  </tr>
  <% @users.each do |user| %>
    <%= content_tag_for :tr, user, :class => cycle(:odd, :even) do %>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <% if current_user.admin? %>
        <td><%= t user.role %></td>
      <% else %>
        <td><%= user.matriculations.collect {|matriculation| matriculation.course.name }.join(", ") %></td>
      <% end %>
      <% if user.last_sign_in_at.present? %>
        <td><%= l user.last_sign_in_at %></td>
      <% else %>
        <td></td>
      <% end %>
    <% end %>
  <% end %>
</table>

app/views/admin/users/allusers.html.erb
<%= content_for :view_all do %>
<h2 class="group-title">Todos Usuários
<spam class="right">Total: <%= @users.count %></spam>
</h2>
<p id="pdf_link" class="right"><%= link_to "Download (PDF)", allusers_admin_users_path(:format => "pdf") %></p>
  <%= render :partial => "usersall" %>
<% end %>

app/views/admin/users/index.html.erb
<h2 class="group-title">Usuários</h2>
  <table>
    <tr>
      <td>
        <div class="field">
          <%= label_tag :data_inicio %>
          <%= text_field_tag :data_inicio, nil, :size => 15, :class => "datepicker" %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= label_tag :data_fim %>
          <%= text_field_tag :data_fim, nil, :size => 15, :class => "datepicker" %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= label_tag "Status" %>
          <%= select "user", "enabled", [["Ativo", 1], ["Desativo", 0]], :include_blank => true %>
        </div>
      </td>
      <% if current_user.teacher? || current_user.tutor? %>
        <td>
          <div class="field">
            <%= label_tag "Curso"  %>
            <%= select "user", "course_id", 
                current_user.teacher? ? current_user.courses.collect {|p| [p.name, p.id]} : 
                current_user.tutors.collect {|p| [p.name, p.id]}, 
                :include_blank => true 
            %>
          </div>
        </td>
      <% end %>
    </tr>
  </table>
  <%= link_to "Pesquisar", admin_users_path, :class => "button", :id => "pesquisar-user", :remote => true %>
<hr class = "thick" />
  <div id="group-users">
    <%= render :partial => "users" %>
  </div>
<hr class = "thick" />

<%= content_for :view_users do %>
  <hr class = "thick" />
  <span class="large title-top">Usuário</span>
  <ul>
    <li><%= link_to "Ver todos Usuários", allusers_admin_users_path, :class => "view_icon", :target => "_blank" %></li>
  </ul>
<% end %>

app/views/admin/users/index.js.erb
$('#group-users').html("<%= escape_javascript(render :partial => "users") %>");

app/views/admin/users/new.html.erb
<h2 class="new-title">Novo Usuário</h2>
<%= render 'form' %>

<%= link_to t('cancel'), admin_users_path %>

app/views/admin/users/show.html.erb
<h2 class="person-title"><%= @user.name %></h2>
<p><strong><i>Email: </i></strong><%= @user.email %></p>

<p><strong><i>Contato: </i></strong><%= @user.contact %></p>
<p><strong><i>Home page: </i></strong><%= !@user.home_page.nil? ? link_to(@user.home_page, url_for(@user.home_page), :target => "_blank") : "N/D"  %></p>
<p><strong><i>Perfil: </i></strong></p>
<div class = "frame">
<%= textilize @user.profile if !@user.profile.nil? %>
</div>

<hr class = "thick" />